services:
  - type: web
    name: pdf-editor
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    disk:
      name: data
      mountPath: /mnt/data
      sizeGB: 1
